version: '3.9'
services:
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            db:
                condition: service_started
        image: wordpress:latest
        volumes:
            - "./source:/var/www/html/"
            - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
        links:
            - db:database
        ports:
            - "0.0.0.0:8000:80"
        restart: on-failure
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

    wpcli:
        image: wordpress:cli
        user: xfs
        volumes:
            - "./source:/var/www/html/"
        links:
            - db:database
        depends_on:
            - db
            - wordpress
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:database
        depends_on: 
            - db
        ports:
            - "0.0.0.0:9119:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress

volumes:
    db_data: {}